### ISSUE TITLE
Clear-Text-Passwörter vermeiden

### ISSUE THREAD

**Issue by GorgeousOne** [asciini/science-camp-2024#1]
Ich denke es wäre eine Überlegung wert die ganzen Zugangsdaten in den Scripten nicht öffentlich auf Github zu lassen. Ist mir zwar auch passiert, aber mein Repo ist halt noch privat. Eine Lösung die ich online gefunden hab, ist einfach ein separates header file mit Passwörtern anzulegen, dass man dann in die gitignore packt: 
https://arduino.stackexchange.com/questions/40411/hiding-wlan-password-when-pushing-to-github

Man muss dann bloß die ganze commit history säubern mit `git commit --amend` (für den letzten commit oder `git rebase -i` (für commits weiter zurück)
https://www.atlassian.com/git/tutorials/rewriting-history

**Comment by asciini** [comment]
Danke für den Hinweis, ich habe die Passwörter aus den Dateien entfernt
